# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v0.1.0-16-ga014464
_src_path: git@github.com:datalab-org/datalab-app-plugin-template
author_email: dev@datalab-org.io
author_fullname: datalab developers
copyright_date: '2025'
copyright_holder: datalab developers
copyright_holder_email: dev@datalab-org.io
package_name: datalab_app_plugin_example
project_name: datalab-app-plugin-example
repository_name: datalab-app-plugin-example
repository_namespace: datalab-org
short_description: datalab-app-plugin-example

